### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by b3zi** [Lanseuo/pydsb#2]
`>>> vp = pydsb.PyDSB("user", "*****")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pydsb.py", line 19, in __init__
    self.entries = self.get_entries()
  File "pydsb.py", line 87, in get_entries
    data = self.data_from_api()
  File "pydsb.py", line 47, in data_from_api
    arguments_gzip = gzip.compress(arguments_json)
AttributeError: 'module' object has no attribute 'compress'
`
Is there someone able to help me?

**Comment by Lanseuo** [comment]
I pushed a new update to GitHub and PyPi. Upgrade pydsb by typing to following:

`pip3 install pydsb --upgrade`

The new API of DSB is not anymore compressed and so GZIP is not anymore required. I hope the new version works for you. Tell me if it doesn't work.
